- .husky/pre-commit
- packages/nextjs/app/about-us/page.tsx
- packages/nextjs/app/contact-us/page.tsx
- packages/nextjs/app/how-it-works/page.tsx
- packages/nextjs/app/layouthola.tsx
- packages/nextjs/app/play/page.tsx
- packages/nextjs/app/principal/page.tsx
- packages/nextjs/app/prizes/page.tsx
- packages/nextjs/components/Footer.tsx
- packages/nextjs/components/Header.tsx
- packages/nextjs/components/Headercopy.tsx
- packages/nextjs/styles/globals.css
- packages/nextjs/tailwind.config.ts
- tailwind.config.js
📂 Cambios Realizados
Implementación del diseño base para las siguientes páginas:
How It Works (/how-it-works)
Play (/play)
Prizes (/prizes)
Contact Us (/contact-us)
About Us (/about-us)
Integración de un Header y Footer con fondo transparente.
> Design of the pages starting

- packages/nextjs/app/about-us/page.tsx
- packages/nextjs/app/contact-us/page.tsx
- packages/nextjs/app/page.tsx
- packages/nextjs/app/prizes/page.tsx
- packages/nextjs/components/Footer.tsx
- packages/nextjs/components/Header.tsx
- packages/nextjs/contracts/deployedContracts.ts
- packages/nextjs/styles/globals.css
- packages/snfoundry/scripts-ts/deploy-contract.ts
- packages/snfoundry/scripts-ts/helpers/deploy-wrapper.ts
- packages/snfoundry/scripts-ts/helpers/fees.ts
- packages/snfoundry/scripts-ts/helpers/networks.ts
- packages/snfoundry/scripts-ts/helpers/parse-deployments.ts
- packages/snfoundry/scripts-ts/verify-contracts.ts
-✅The prize page is complete
-➕Add links in the github footer and x
> Prizes page ready

- packages/nextjs/app/contact-us/page.tsx
- packages/nextjs/app/play/page.tsx
- packages/nextjs/components/Header.tsx
- packages/nextjs/components/scaffold-stark/CustomConnectButton/ConnectModal.tsx
- packages/nextjs/components/scaffold-stark/CustomConnectButton/index.tsx
Adding funtionality to connect wallet in buttons
I have updated buttons in header and play when we click on them the connect wallet window is showed
> feat-adding funtionality to connect wallet in buttons

- packages/nextjs/app/_components/contractByApp/ContractProfileUI.tsx
- packages/nextjs/app/_components/contractByApp/ContractReadMethods.tsx
- packages/nextjs/app/_components/contractByApp/ContractWriteMethods.tsx
- packages/nextjs/app/_components/contractByApp/GetTicketInfoForm.tsx
- packages/nextjs/app/_components/contractByApp/GetTicketUserForm.tsx
- packages/nextjs/app/_components/contractByApp/ProfileTicketsInfo.tsx
- packages/nextjs/app/_components/contractByApp/TicketInfoDisplay.tsx
- packages/nextjs/app/_components/contractByApp/utilsDisplay.tsx
- packages/nextjs/app/play/confirmation/page.tsx
- packages/nextjs/app/profile/page.tsx
- packages/nextjs/components/Header.tsx
- packages/nextjs/interfaces/global/index.ts
- packages/nextjs/services/store/contractFn.ts
- packages/nextjs/utils/Constants.ts
Fixes #relevant-issue-here
The user profile page was created, allowing users to check if they have purchased any tickets and view the exact ticket along with its basic information.
> Profile page UI has been created with Smart Contract

- packages/nextjs/app/_components/contractByApp/BuyTicketForm.tsx
- packages/nextjs/app/_components/contractByApp/GetTicketUserForm.tsx
- packages/nextjs/app/play/page.tsx
- packages/nextjs/utils/scaffold-stark/notification.tsx
🤖Colors were adjusted for greater contrast and visual clarity.
> Adjustment of styles in notifications

- README.md
Add Readme in dev branch
Closes #21 
Require documentation in dev branch
> Add README in branch dev

- packages/nextjs/components/Header.tsx
Please provide a summary of the changes and the reason behind them.
Closes #
1. 🔹 Step 1
2. 🔹 Step 2
3. 🔹 Step 3
> fix header responsiveness as in the image provided

- packages/snfoundry/contracts/Scarb.lock
- packages/snfoundry/contracts/Scarb.toml
- packages/snfoundry/contracts/src/LotteryERC20.cairo
- packages/snfoundry/contracts/src/lib.cairo
- packages/snfoundry/contracts/src/test/LotteryERC20.cairo
This PR add utility token smart contract, initial supply is 21 millions, symbol is `STRKP`, name is `$starkPlay`
The following tests have been added:
- Ensure only admin can mint
- Ensure can't burn more than balance
- Ensure can't transfer_from more than allowance/balance
- Ensure can't transfer more than balance
- Ensure Burn event is emitted 
- Ensure Mint event is emitted
- Ensure allowance is decremented after transfer_from
This token will serve as the main utility token within our ecosystem
Closes #44
> feat: add utility token

- packages/nextjs/app/contact-us/page.tsx
Update Contact Us page to look as the figma designs  (desktop and mobile)
Note: Header will be fixed on a separate issue/PR
Make the page look good/adequate at different resolutions
Closes #32 
1. 🔹 Step 1: Open figma file to check Desktop and Mobile view of that page
2. 🔹 Step 2: Run the app locally and go to the `Contact Us` page
3. 🔹 Step 3: Compare implementation in different viewports
**DESKTOP**
**MOBILE**
- I did not change any behavior of the form
- The font is different than the used in the design specs that's why the title and subtitle look different
- Once the header gets fixed, it will look much better
- Had to import the Telegram icon inserting the SVG code because heroicons does not have that icon available
> [FEAT: ]Fix Contact Us responsiveness

- user-profile.md
I created a design for the user profile and added the link to the figma in the user-profile.md file
Allows users to easily access their details
Closes #42 
@drakkomaximo 
This is the new pull request and the base is at the dev branch. Please review
> feat: user profile layout design

- CHANGESLOG.md
This PR adds a `CHANGELOG.md` file to the repository following the [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) format. The changelog will help maintain a clear record of changes, improvements, and fixes, improving transparency and communication for developers, contributors, and users.
- Added a `CHANGELOG.md` file in the root directory.
- Included example entries for each category (`Added`, `Changed`, `Deprecated`, `Removed`, `Fixed`, `Security`) to demonstrate the structure.
- Followed the Keep a Changelog guidelines to ensure consistency and clarity.
A changelog is essential for:
- Keeping track of project updates and versions.
- Making it easier for contributors and users to understand what has changed between releases.
- Enhancing transparency and trust in the development …
> CHANGESLOG.md

- packages/nextjs/.env.example
- packages/nextjs/app/admin/layout.tsx
- packages/nextjs/app/admin/page.tsx
- packages/nextjs/components/StepTracker.tsx
- packages/nextjs/components/scaffold-stark/CustomConnectButton/GenericModal.tsx
- packages/nextjs/components/sweepstakes/ContentDisplay.tsx
- packages/nextjs/components/sweepstakes/FormStep.tsx
- packages/nextjs/components/sweepstakes/ReviewStep.tsx
- packages/nextjs/components/sweepstakes/index.tsx
- packages/nextjs/components/ui/button.tsx
- packages/nextjs/layout/Sidebar.tsx
- packages/nextjs/layout/Topbar.tsx
- packages/nextjs/layout/_data.ts
- packages/nextjs/services/store/sweepstakesStore.ts
- packages/nextjs/styles/globals.css
- packages/nextjs/utils/validations/sweepstakesSchema.ts
- Created a fresh path from `/admin` to contain all admin related issues
- created a `layout` folder at the base to enable handling the layout of each path easier
- modified the generic modal for better integration.
- created the `sweepstakes` path to manage the staking parameters
- able to create and confirm sweepstakes
- better modal handling for open and close states
Closes #91
The video implementation link
[Click here](https://drive.google.com/file/d/1cZ4WJQhoOl1Z7vbiZt8FXNnhyB-ddYNp/view?usp=sharing)
> feat: add admin route and sweepstakes management

- packages/nextjs/app/admin/UsersCard.tsx
Introduces a new UsersManagementCard component for the admin dashboard, providing a quick access point to user management functionality.
This PR addresses the missing "Users" management section in the admin panel. Currently, administrators lack a centralized entry point to access and manage system users, creating friction in the user management workflow.
The new Users Management Card provides a clearly identifiable access point with intuitive navigation, reducing the number of clicks needed to perform user management tasks. By adding this component to the admin dashboard, we're completing a critical part of the admin interface that aligns with the existing design system and improves overall administrative efficiency.
This …
> Feat/new user panel #106

- packages/snfoundry/contracts/Scarb.lock
- packages/snfoundry/contracts/Scarb.toml
- packages/snfoundry/contracts/src/LottoTicketNFT.cairo
- packages/snfoundry/contracts/src/lib.cairo
Implementation Ticket NFT Contract
1. 🔹 Step 1
2. 🔹 Step 2
3. 🔹 Step 3
> Implementation Ticket NFT Contract

- packages/snfoundry/contracts/src/Lottery.cairo
This PR adds the necessary flow to process the payment of the tickets.
It is necessary to process the buying process of the tickets from the lottery.
Closes #151 
Let me know if any additional changes are necessary! :D
> feat: implement ticket purchase function

- packages/snfoundry/contracts/src/StarkPlayERC20.cairo
- packages/snfoundry/contracts/src/lib.cairo
- packages/snfoundry/contracts/tests/test_erc20.cairo
There is a contract error, the pause and unpause functions are private functions and as such they are not exposed for testing. Secondly i commented the is_contract assertion, because it was always returning an entry point failure. How do we resolve both?
@davidmelendez 
Closes #
1. 🔹 Step 1
2. 🔹 Step 2
3. 🔹 Step 3
> Test mint and burn starkplayerc20

- docs/ADMIN/FEE_MINT_STARKP_MANAGEMENT.md
- docs/ADMIN/README.md
- packages/snfoundry/contracts/Scarb.toml
- packages/snfoundry/contracts/src/Lottery.cairo
- packages/snfoundry/contracts/src/StarkPlayVault.cairo
- packages/snfoundry/contracts/tests/test_CU01.cairo
Implementation of comprehensive unit tests for fee range validation in StarkPlayVault contract, including event emission verification using spy_events. This PR addresses ISSUE-TEST-004 by adding robust testing coverage for fee management functionality and administrator documentation.
The StarkPlayVault contract handles critical fee validation logic that needs thorough testing to ensure security and proper behavior. Previously, there was insufficient test coverage for:
- Fee range validation (minimum and maximum limits)
- Event emission verification for fee changes
- Edge cases and boundary value testing
- Administrator documentation for fee management
This change provides comprehensive test coverage and professional documentation to ensure the fee management system works correctly and …
> test: fee mint range validation

- packages/snfoundry/contracts/src/StarkPlayVault.cairo
- packages/snfoundry/contracts/tests/test_CU01.cairo
- packages/snfoundry/contracts/tests/test_mint_strk_play.cairo
This test suite verifies the integration between the StarkPlayVault and StarkPlayERC20 contracts on Starknet. It covers deployment, minting permissions, minting behavior (including edge cases), event emission, and fee management. The tests ensure secure token issuance and correct protocol fee enforcement.
Closes #247 
1. 🔹 Step 1
2. 🔹 Step 2
3. 🔹 Step 3
> ISSUE-TEST-008: Test successful $tarkPlay minting

- packages/snfoundry/contracts/.tool-versions
- packages/snfoundry/contracts/src/Lottery.cairo
- packages/snfoundry/contracts/tests/lib.cairo
- packages/snfoundry/contracts/tests/test_jackpot_history.cairo
> Feat: 🎰 Add Jackpot History Query Function

- packages/snfoundry/contracts/src/StarkPlayVault.cairo
- packages/snfoundry/contracts/tests/test_CU01.cairo
- packages/snfoundry/contracts/tests/test_inventory.md
> test: Test correct fee calculation in transactions

- packages/snfoundry/contracts/src/StarkPlayVault.cairo
- packages/snfoundry/contracts/tests/test_CU01.cairo
> Test: Test correct 1:1 conversion in buySTRKP

- packages/snfoundry/contracts/src/StarkPlayVault.cairo
- packages/snfoundry/contracts/tests/test_CU01.cairo
Closes #188 
Adds functions to handle prize conversion fee percentage in StarkPlayVault contract. This includes new getter and setter functions with proper validation, events, and comprehensive tests for the fee management system.
The StarkPlayVault contract needed additional functionality to manage prize conversion fees separately from other fees. This enhancement provides:
- **Flexible fee management** for prize conversions with independent control
- **Proper validation** to ensure fee percentages stay within acceptable bounds
- **Event emission** for transparency and tracking of fee changes
- **Comprehensive testing** to ensure reliability of the new functionality
This feature is essential for maintaining proper fee structure and providing granular control over different types of fees …
> feat: Implement Fee Update Functions with Access Control

- packages/nextjs/app/results/[drawId]/page.tsx
- packages/nextjs/app/results/page.tsx
- packages/nextjs/components/LastDrawResults.tsx
- packages/nextjs/components/jackpot/DrawHistoryTable.tsx
- packages/nextjs/components/results/DrawDetails.tsx
- packages/nextjs/components/results/PrizeBreakdown.tsx
- packages/nextjs/data/mockData.ts
- packages/nextjs/hooks/useTableSorting.ts
- packages/nextjs/services/api/drawsService.ts
- packages/nextjs/types/results.ts
close #205 
This pull request implements a comprehensive detailed view for specific lottery draws, allowing users to explore past or selected draws in depth. The feature provides complete transparency and clarity on how prizes were allocated, including winning numbers, prize distribution, winner statistics, and rollover information.
The application previously only showed basic draw results without detailed breakdowns. Users needed a way to:
- View comprehensive details of specific draws
- Understand prize distribution across different tiers
- See transparency in prize allocation
- Navigate between draw history and detailed views seamlessly
This feature addresses the need for complete transparency in lottery operations and provides users with detailed insights into how prizes are …
> Feat/selected draw UI 205

- packages/snfoundry/contracts/.tool-versions
- packages/snfoundry/contracts/tests/test_starkplay_balance.cairo
> 🧪 Add Comprehensive Test Suite for StarkPlay ERC20 Token Balance Management

- packages/nextjs/app/how-it-works/page.tsx
- packages/nextjs/app/page.tsx
- packages/nextjs/components/PrizeDistribution.tsx
- packages/nextjs/components/sections/PrizeDistributionSection.tsx
- packages/nextjs/components/sections/index.ts
- packages/nextjs/data/prizeDistribution.ts
close #204 
Implemented a new "Prize Distribution" section on the Starklotto platform to clearly present how the prize pool is distributed across different winning tiers. This section provides transparency and helps users understand how rewards are calculated based on the number of correct picks.
The implementation includes:
- A reusable `PrizeDistribution` component with visual representation of prize tiers
- Integration into both the homepage and `/how-it-works` page
- Centralized data configuration for easy maintenance
- Responsive design with animations and accessibility features
Previously, there was no dedicated section explaining how prizes are divided by match count, leaving users unclear about reward calculations for each draw. This feature addresses this gap by providing:
- …
> feat: add Prize Distribution section and related components

- packages/snfoundry/contracts/tests/test_starkplay_vault.cairo
- Added multiple tests to verify event emissions during token purchases, including checks for emitted events, event parameter validation, and event order consistency.
- Implemented helper functions for expected fee and minted amount calculations.
- Improved test coverage for various scenarios, including transactions with different users, large amounts, and error cases.
- Updated approval logic to allow for a larger token allowance to ensure successful transactions.
Closes #249
> test: enhance event testing in StarkPlayVault contract

- packages/snfoundry/contracts/src/StarkPlayVault.cairo
- packages/snfoundry/contracts/tests/test_starkplay_vault.cairo
This test suite adds **comprehensive validation** for the StarkPlay vault's internal counter tracking mechanisms. It verifies that:
- `total_starkplay_minted`
- `total_strk_stored`
- `accumulated_fee`
are accurately maintained across **single and multiple user transactions**, ensuring data integrity and consistency in the vault's accounting system.
These tests are essential for validating the vault's **core accounting functionality**. The counters track critical financial data including:
- Total tokens minted
- Total STRK stored
- Accumulated fees
Closes #245 
1. 🔹 Step 1
2. 🔹 Step 2
3. 🔹 Step 3
> ISSUE-TEST-011: Test contract counters update

- packages/snfoundry/contracts/tests/test_buy_ticket.cairo
This PR implements a comprehensive test suite for the `BuyTicket` function in the Lottery contract with **35+ exhaustive tests** covering successful cases, input validations, error handling, edge cases, overflow protection, and integration testing. The implementation addresses hardcoded contract address dependencies using snforge's contract mocking capabilities.
The BuyTicket function is a critical component handling user ticket purchases, token transfers, and state management. Previously, there was insufficient test coverage creating risks for:
- **Financial Operations**: Unvalidated token transfers and balance checks
- **Input Validation**: No verification of number selections and user inputs  
- **Business Logic**: Unchecked draw status and ticket creation logic
- **Integration …
> Fix: ISSUE-003-CU03

- packages/nextjs/contracts/deployedContracts.ts
- packages/snfoundry/contracts/src/Lottery.cairo
- packages/snfoundry/contracts/tests/test_CU01.cairo
- packages/snfoundry/contracts/tests/test_CU03.cairo
- packages/snfoundry/contracts/tests/test_buy_ticket.cairo
- packages/snfoundry/contracts/tests/test_inventory.md
- packages/snfoundry/contracts/tests/test_jackpot_history.cairo
- packages/snfoundry/scripts-ts/deploy.ts
Closes #325 
A full refactor of the Lottery contract has been implemented to support dynamic addresses for the StarkPlayERC20 and StarkPlayVault contracts. Changes include:
* **Modified the Lottery contract constructor** to accept dynamic addresses instead of hardcoded constants
* **Updated the deployment script** to deploy contracts in the correct order and pass dynamic addresses
* **Refactored all tests** to adapt to the new constructor while preserving full functionality
* **Improved deployment flexibility** by removing the need to recompile the contract when addresses change
The main issue was that the Lottery contract had the StarkPlayERC20 and StarkPlayVault addresses hardcoded as constants, limiting deployment flexibility and requiring recompilation each time the addresses changed. …
> Refactor Lottery Contract: Dynamic Address Implementation

- packages/snfoundry/contracts/tests/test_CU01.cairo
Implemented comprehensive test suite for mint and burn authorization in StarkPlayERC20 contract, covering role management, authorized operations, security limits, and integration scenarios.
This change ensures the role-based access control system in StarkPlayERC20 works correctly and securely. The tests verify that only authorized contracts can mint/burn tokens and that proper security measures are in place.
Closes #138
1. 🔹 Run role management tests: `snforge test test_owner`
2. 🔹 Run authorization tests: `snforge test test_authorized_contract`
3. 🔹 Run security tests: `snforge test test_mint_limit`
4. 🔹 Run integration tests: `snforge test test_vault_integration`
Tests cover all requirements from ISSUE-BC-AUTH-002:
- Role management (grant/revoke MINTER_ROLE and BURNER_ROLE)
- …
> Adding an extensive set of tests for starkplayerc20 burn and mint functionalities

- packages/snfoundry/contracts/src/StarkPlayVault.cairo
- packages/snfoundry/contracts/tests/test_CU02.cairo
Implemented critical security validations in the `convert_to_strk` function of the StarkPlayVault contract to prevent reentrancy attacks and ensure robust input validation. The function now follows the Checks-Effects-Interactions pattern and includes comprehensive security measures.
* Security validations were implemented in the `convert_to_strk` function: reentrancy protection and zero address validation.
* A helper function `zero_address_const()` was added for zero address validation.
* Contract balance verification was added before STRK transfers to prevent failed transactions.
* Unit tests were added to verify the correct behavior of all security validations.
* The existing reentrancy test was corrected to properly verify the protection pattern.
The `convert_to_strk` function …
> feat: Reentrancy protection and zero address validation in the convert_to_strk function

- packages/nextjs/components/LastDrawResults.tsx
- packages/nextjs/components/ui/ErrorMessage.tsx
- packages/nextjs/components/ui/LoadingSkeleton.tsx
- packages/nextjs/hooks/useLatestDraw.ts
- packages/nextjs/i18n/locales/en.json
- packages/nextjs/i18n/locales/es.json
- packages/nextjs/i18n/locales/fr.json
- packages/nextjs/i18n/locales/pt.json
- packages/nextjs/services/draw.service.simple.ts
- packages/nextjs/services/draw.service.ts
close #202 
Fully functional system that automatically queries and displays the latest lottery draw results without requiring manual refresh. The "Last Draw Results" section stays always up to date with real-time simulated data.
- **Frequency**: Queries new data every 10 seconds
- **Auto-start**: Activates 2 seconds after initial load
- **Change detection**: Identifies new draws and updates UI
- **No manual intervention**: Users don't need to refresh the page
- **Initial load**: Shows data immediately when visiting the page
- **New draws**: Generated every 15 seconds for demonstration
- **Smooth transitions**: Animations with Framer Motion
- **Notifications**: Toast and visual banner for new results
- **Retry logic**: 3 automatic attempts with exponential backoff
- **Error types**: …
> Enhance LastDrawResults

- packages/snfoundry/contracts/src/Lottery.cairo
Draw IDs are being validated in places where Draw IDs are used, and an event is emmitted depending on the validation state of the Draw ID that fails.
This saves processing invalid Draws
Closes #459 
1. 🔹 Git Checkout </>
2. 🔹 Set required tools as specified in `.tool-versions`
3. 🔹 `nforge test`
> Draw id validation

- packages/snfoundry/contracts/tests/test_ticket_recording.cairo
Provides Integration tests for the Token transfer from a user to the lottery vault, during ticket purchase.
This ensures value is exchanged properly between the user and the protocol.
Closes #460
1. 🔹 Git Checkout
2. 🔹 Setup Dev Environment
3. 🔹 snforge test
> dev: ISSUE-TEST-003: Token Transfer Integration Tests

- packages/snfoundry/contracts/src/Lottery.cairo
- packages/snfoundry/contracts/tests/test_CU03.cairo
- packages/snfoundry/contracts/tests/test_ticket_recording.cairo
> Fix Multiple Critical Issues in BuyTicket

- packages/snfoundry/contracts/src/Lottery.cairo
- packages/snfoundry/contracts/tests/test_CU03.cairo
- packages/snfoundry/contracts/tests/test_basic_functions.cairo
- packages/snfoundry/contracts/tests/test_lottery_getters.cairo
This PR implements comprehensive unit tests for all getter functions in the Lottery.cairo contract that previously lacked testing coverage. It addresses the issue by creating extensive test suites that validate every getter function, ensuring data consistency, handling edge cases, and maintaining proper business logic validation.
The Lottery.cairo contract had multiple getter functions without specific unit tests, representing a significant risk for query function validation. This implementation provides complete testing coverage for all getter functions including `GetTicket*`, `GetJackpotEntry*`, and other query functions, ensuring they return correct values in all scenarios.
Closes #458 
1. 🔹 Run `scarb test` to execute all tests including the new getter function tests
2. 🔹 Verify that …
> test: Comprehensive Getter Function Tests Lottery

- packages/snfoundry/contracts/src/StarkPlayERC20.cairo
This PR addresses the contract validation issue in StarkPlayERC20 by implementing a comprehensive security analysis and simplifying the validation approach. After extensive research and multiple implementation attempts, we concluded that complex contract type validation is unnecessary and potentially insecure, opting instead for a role-based access control approach that leverages existing security mechanisms.
The original issue requested implementation of SRC5 interface validation for contract verification. However, after conducting thorough security analysis using AI assistance tools and reviewing the existing codebase architecture, we discovered that:
1. **Security already exists**: The system uses robust role-based access control (RBAC) where only authorized addresses can perform …
> Simplify Contract Validation in StarkPlayERC20
